modified xxhpass so it still kinda works even when xxhsum isn't found

diff --git a/xxhpass b/xxhpass
--- a/xxhpass
+++ b/xxhpass
@@ -3,5 +3,6 @@
 if [ -n "$(which xxhsum)" ]; then
 	tee >(xxhsum 1>&2)
 else
-	echo "xxhsum not found"
+	1>&2 echo "xxhsum not found"
+	cat
 fi
